# Site settings
title: hathix.com
description: hathix.com is home to Neel Mehta's software, blog, portfolio, and more. Think inside the box.
url: http://hathix.com
angular_version: 1.3.13
bootstrap_version: 3.3.7
bootswatch_theme: journal
jquery_version: 1.12.4 # bootstrap doesn't allow jQuery v3+

# Build settings
markdown: kramdown
permalink: pretty

plugins:
 - jekyll-coffeescript
