# Site settings
tagline: "hathix.com"

title: Jekyll - Angular - Firebase (JAF)
email: your-email@domain.com
description: "your site description"
url: "http://hathix.com"
angular_version: 1.3.8
bootstrap_version: 3.3.1
jquery_version: 1.11.2
fontawesome_version: 4.2.0

# Build settings
markdown: kramdown
permalink: pretty
