# Site settings
tagline: "hathix.com"

title: hathix.com
description: hathix.com is home to Neel Mehta's software, blog, portfolio, and more. Think inside the box.
url: http://hathix.com
angular_version: 1.3.13
bootstrap_version: 3.3.6
jquery_version: 1.11.3
fontawesome_version: 4.5.0

# Build settings
markdown: kramdown
permalink: pretty
